ログは常に出力するように変更

diff --git a/.github/workflows/image-test.yml b/.github/workflows/image-test.yml
--- a/.github/workflows/image-test.yml
+++ b/.github/workflows/image-test.yml
@@ -102,7 +102,9 @@ jobs:
       - name: Test Docker Image
         id: image-test
         run: |
-          docker exec -u developer -t ${{ env.IMAGE_NAME_CORE }} bash -l -c "cd src/burger_war_kit && bash scripts/sim_run_test.sh"
+          docker exec -u developer -t ${{ env.IMAGE_NAME_CORE }} bash -l -c "cd src/burger_war_kit && bash scripts/sim_run_test.sh" \
+            && echo "::set-output name=test_result::0" \
+            || echo "::set-output name=test_result::1"
 
       # テスト結果をArtifactにアップロードする
       - name: Upload Artifact
@@ -114,6 +116,7 @@ jobs:
 
       # ghcr.ioにログイン
       - name: Login to ghrc.io
+        if: steps.image-test.outputs.test_result == 0
         uses: docker/login-action@v1
         with:
           registry: ghcr.io
@@ -122,6 +125,7 @@ jobs:
 
       # burger-warイメージをテストバージョンとしてプッシュ
       - name: Push Docker Image
+        if: steps.image-test.outputs.test_result == 0
         run: |
           # burger-war-simのプッシュ
           docker tag ${{ env.IMAGE_NAME_SIM }} ${{ env.RESISTRY_URL }}/${{ env.IMAGE_NAME_SIM }}:${{ env.TEST_VERSION }}
@@ -130,3 +134,10 @@ jobs:
           docker tag ${{ env.IMAGE_NAME_ROBO }} ${{ env.RESISTRY_URL }}/${{ env.IMAGE_NAME_ROBO }}:${{ env.TEST_VERSION }}
           docker push ${{ env.RESISTRY_URL }}/${{ env.IMAGE_NAME_ROBO }}:${{ env.TEST_VERSION }}
 
+      # テストがNGだった場合
+      - name: If Test Failed
+        if: steps.image-test.outputs.test_result != 0
+        run: |
+          echo "::error Test Is Faild!!"
+          echo "::error See step 'Test Docker Image'"
+          exit 1
